### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by olimart** [Riskified/timeasure#3]
Hi,
Great work! (and the articles on Medium helping understand how it works).

Out of curiosity, what would it take to track not just the overall time elapsed but time spent in each part  (SQL, controller, view, painting...) and potentially N+1 queries.

In other words, would it be possible to build something similar to [Skylight.io](https://skylight.io) (I mean sending off enough data) with Timeasure?

Thanks.

**Comment by eliavlavi** [comment]
Thanks a lot!
So Timeasure is aimed at solving a rather simple problem - allowing you to track the runtime of methods in your code, easily. The choice of how and with which tool to analyze this data is left for the you. Some might use Tableau, others NewRelic, some might pick Keen.io, or any other analytics service.
As far as **what** you are measuring is concerned, well, as long as it's a method in Ruby, it is measurable, whether it's part of a view, a controller, a model or any other object you might have in your app. At the end of the process you've got the aggregated runtime of each tracked method available to you.

It seems to me that Skylight.io is aspiring to be a rather broad optimization-solution, helping developers maintain better-performing Rails apps from several perspectives. I see they declare in their website that they deliver "ANSWERS, NOT DATA" - Timeasure's agenda is quite the other way around - data, not answers. You get an easy way to **gather** the data - **how** to analyze it is left for you to decide. Then you can figure out how to refactor your code accordingly and improve performance.

I hope that makes sense and answers your question!
Cheers,
Eliav

**Comment by olimart** [comment]
👍
